batch_size: 128
seq_len: 100
predict_len: 0
label_len: 0
do_eval: True
epoch: 1
training: True 
anomaly_ratio: 1
task: anomaly


dataset: 
  name: TSADDataset
  dataset_root: ../data/
  train_path: ../data/PMS_train.csv
  val_path: ../data/PMS_test.csv
  scale: True
  time_feat: False

info_params:
  freq: 1
  time_col: timestamp
  feature_cols: ['feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24']
  label_col: label

model: 
  name: DLinear_AD
  model_cfg:
    optimizer_params:
      learning_rate: 0.001
      gamma: 0.5

loss: mse

test:
  stride: 1 

output_dir: 'output_dl_ad/'
