batch_size: 32
seq_len: 96
predict_len: 96
sampling_stride: 1
do_eval: True
epoch: 10

dataset: 
  name: TSDataset
  dataset_root: /ETTh1/
  train_path: /ETTh1/train.csv
  val_path: /ETTh1/val.csv
  time_feat: False
  scale: True

info_params:
  time_col: date
  target_cols: ['HUFL','HULL','MUFL','MULL','LUFL','LULL','OT']
  freq: 1h

model: 
  name: DLinearModel
  model_cfg:
    c_in: 7
    individual: False
    optimizer_params:
      learning_rate: 0.005
      gamma: 0.5
    patience: 3

test:
  stride: 1

  



